In [15]:
import numpy as np
from hMDS.embedding import hmds, poincare_dist
from hMDS.utils import distortion

# Original distance matrix
A = np.array([
              [0.,  6,  8,  9,  10, 11, 12, 12], 
              [6.,  0,  6,  7,  8,  9,  10, 10],
              [8.,  6,  0,  7,  8,  9,  10, 10],
              [9.,  7,  7,  0,  7,  8,  9,  9],
              [10,  8,  8,  7,  0,  5,  6,  6],
              [11,  9,  9,  8,  5,  0,  5,  5],
              [12, 10, 10,  9,  6,  5,  0,  4],
              [12, 10, 10,  9,  6,  5,  4,  0],
            ])
# Run hMDS
scale = 1
Xrec = hmds(A, k=8, scale=scale)

print(f">> Embeddings in the Poincaré Ball of dimension r = {Xrec.shape[1]}")

# Compute the reconstructed distance matrix
n = A.shape[0]
Hrec = np.zeros_like(A)
for i in range(n):
    for j in range(n):
        Hrec[i,j] = poincare_dist(Xrec[i], Xrec[j])/scale

print(">> Recovered pairwise distances:")
print(np.round(Hrec, 2))

# Evaluate the distortion
dist = distortion(A, Hrec, n=8)
print(f'>> Average distortion = {np.round(dist["avg_distortion"], 2)}, best average distortion is 0.')
print(f'>> Worst-case distortion = {np.round(dist["wc_distortion"], 2)}, best worst-case distortion is 1.')


Launching h-mds ...
found 7 dimensions
Time Elapsed = 0.0
>> Embeddings in the Poincaré Ball of dimension r = 7
>> Recovered pairwise distances:
[[ 0.  6.  8.  9. 10. 11. 12. 12.]
 [ 6.  0.  6.  7.  8.  9. 10. 10.]
 [ 8.  6.  0.  7.  8.  9. 10. 10.]
 [ 9.  7.  7.  0.  7.  8.  9.  9.]
 [10.  8.  8.  7.  0.  5.  6.  6.]
 [11.  9.  9.  8.  5.  0.  5.  5.]
 [12. 10. 10.  9.  6.  5.  0.  4.]
 [12. 10. 10.  9.  6.  5.  4.  0.]]
>> Average distortion = 0.0, best average distortion is 0.
>> Worst-case distortion = 1.0, best worst-case distortion is 1.


# Embedding in the Poincaré Disk k=2

The Poincaré Disk is a hyperbolic space of only 2 dimensions. We can see how embedding in this space increases the distortion.

In [21]:
# Run hMDS
scale = 1
Xrec = hmds(A, k=2, scale=scale)

print(f">> Embeddings in the Poincaré Ball of dimension r = {Xrec.shape[1]}")

# Compute the reconstructed distance matrix
n = A.shape[0]
Hrec = np.zeros_like(A)
for i in range(n):
    for j in range(n):
        Hrec[i,j] = poincare_dist(Xrec[i], Xrec[j])/scale

print(">> Recovered pairwise distances:")
print(np.round(Hrec, 2))

# Evaluate the distortion
dist = distortion(A, Hrec, n=8)
print(f'>> Average distortion = {np.round(dist["avg_distortion"], 2)}, best average distortion is 0.')
print(f'>> Worst-case distortion = {np.round(dist["wc_distortion"], 2)}, best worst-case distortion is 1.')


Launching h-mds ...
found 2 dimensions
Time Elapsed = 0.0
>> Embeddings in the Poincaré Ball of dimension r = 2
>> Recovered pairwise distances:
[[ 0.    3.18  6.95  8.6   9.6  10.86 11.96 11.96]
 [ 3.18  0.    3.87  5.82  7.35  8.66  9.78  9.78]
 [ 6.95  3.87  0.    3.58  7.14  8.58  9.74  9.74]
 [ 8.6   5.82  3.58  0.    5.85  7.39  8.58  8.58]
 [ 9.6   7.35  7.14  5.85  0.    1.6   2.83  2.83]
 [10.86  8.66  8.58  7.39  1.6   0.    1.24  1.24]
 [11.96  9.78  9.74  8.58  2.83  1.24  0.    0.  ]
 [11.96  9.78  9.74  8.58  2.83  1.24  0.    0.  ]]
>> Average distortion = 0.21, best average distortion is 0.
>> Worst-case distortion = 4.03, best worst-case distortion is 1.
