In [1]:
import numpy as np
from hMDS.embedding import hmds, poincare_dist
from hMDS.utils import distortion

# Original distance matrix
A = np.array([
              [0.,  6,  8,  9,  10, 11, 12, 12], 
              [6.,  0,  6,  7,  8,  9,  10, 10],
              [8.,  6,  0,  7,  8,  9,  10, 10],
              [9.,  7,  7,  0,  7,  8,  9,  9],
              [10,  8,  8,  7,  0,  5,  6,  6],
              [11,  9,  9,  8,  5,  0,  5,  5],
              [12, 10, 10,  9,  6,  5,  0,  4],
              [12, 10, 10,  9,  6,  5,  4,  0],
            ])
# Run hMDS
scale = 1
Xrec = hmds(A, k=8, scale=scale)

print(f">> Embeddings in the Poincaré Ball of dimension r = {Xrec.shape[1]}")

# Compute the reconstructed distance matrix
n = A.shape[0]
Hrec = np.zeros_like(A)
for i in range(n):
    for j in range(n):
        Hrec[i,j] = poincare_dist(Xrec[i], Xrec[j])/scale

print(">> Recovered pairwise distances:")
print(np.round(Hrec, 2))

# Evaluate the distortion
dist = distortion(A, Hrec, n=8)
print(f'>> Average distortion = {np.round(dist["avg_distortion"], 2)}, best average distortion is 0.')
print(f'>> Worst-case distortion = {np.round(dist["wc_distortion"], 2)}, best worst-case distortion is 1.')


Launching h-mds ...
found 7 dimensions
Time Elapsed = 0.0051152706146240234
>> Embeddings in the Poincaré Ball of dimension r = 7
>> Recovered pairwise distances:
[[ 0.  6.  8.  9. 10. 11. 12. 12.]
 [ 6.  0.  6.  7.  8.  9. 10. 10.]
 [ 8.  6.  0.  7.  8.  9. 10. 10.]
 [ 9.  7.  7.  0.  7.  8.  9.  9.]
 [10.  8.  8.  7.  0.  5.  6.  6.]
 [11.  9.  9.  8.  5.  0.  5.  5.]
 [12. 10. 10.  9.  6.  5.  0.  4.]
 [12. 10. 10.  9.  6.  5.  4.  0.]]
>> Average distortion = 0.0, best average distortion is 0.
>> Worst-case distortion = 1.0, best worst-case distortion is 1.


# Embedding in the Poincaré Disk k=2

The Poincaré Disk is a hyperbolic space of only 2 dimensions. We can see how embedding in this space increases the distortion.

In [2]:
# Run hMDS
scale = 1
Xrec = hmds(A, k=2, scale=scale)

print(f">> Embeddings in the Poincaré Ball of dimension r = {Xrec.shape[1]}")

# Compute the reconstructed distance matrix
n = A.shape[0]
Hrec = np.zeros_like(A)
for i in range(n):
    for j in range(n):
        Hrec[i,j] = poincare_dist(Xrec[i], Xrec[j])/scale

print(">> Recovered pairwise distances:")
print(np.round(Hrec, 2))

# Evaluate the distortion
dist = distortion(A, Hrec, n=8)
print(f'>> Average distortion = {np.round(dist["avg_distortion"], 2)}, best average distortion is 0.')
print(f'>> Worst-case distortion = {np.round(dist["wc_distortion"], 2)}, best worst-case distortion is 1.')


Launching h-mds ...
found 2 dimensions
Time Elapsed = 0.0005154609680175781
>> Embeddings in the Poincaré Ball of dimension r = 2
>> Recovered pairwise distances:
[[ 0.    3.    7.48  8.7   9.97 11.   12.   12.  ]
 [ 3.    0.    5.3   6.64  7.96  8.99  9.99  9.99]
 [ 7.48  5.3   0.    5.95  7.93  8.96  9.96  9.96]
 [ 8.7   6.64  5.95  0.    6.76  7.79  8.8   8.8 ]
 [ 9.97  7.96  7.93  6.76  0.    1.21  2.24  2.24]
 [11.    8.99  8.96  7.79  1.21  0.    1.03  1.03]
 [12.    9.99  9.96  8.8   2.24  1.03  0.    0.  ]
 [12.    9.99  9.96  8.8   2.24  1.03  0.    0.  ]]
>> Average distortion = 0.17, best average distortion is 0.
>> Worst-case distortion = 4.86, best worst-case distortion is 1.
